info = {
    "Pentru a spala bani murdari ai nevoie de o afacere!",
    "Patronul se poate cumpara cu diamante!",
    -- "Daca explodezi artificiile primesti bani!",
    "Economia este Hard RolePlay",
    "Daca te-ai plictisit, du-te si fa un job! (/jobs)",
    "Foloseste comanda [/jobs] pentru a ajunge la birouri",
    "Daca vrei sa iti faci un Gang, aplica pe discord ca (Lider Gang)",
    "Iti recomand jobul de Aprovizionari [/jobs]",
    "Asigura-te ca ai citit regulamentul!",
    -- "Cutia de artificii explodeaza daca o calci cu masina!",
    "Daca ai un job, ai o masina!",
    "Poti cumpara un SmartPhone de la magazin",
    "Poti fi patron la un job, vei primii incasari cand cineva lucreaza acolo!",
    "Poti gasii diverse locatii pe GPS (k>GPS)",
    "Daca vrei sa iti faci un Gang, aplica pe discord ca (Lider Gang)",
    "k>GPS>[Job Center] pentru a te angaja",
    "Iti Recomand Jobul de Aprovizionari",
    "Te poti face Car Dealer cand ai 10 ore (ai nevoie de un pistol)",
    "Comanda la taxi se face doar prin apel (k/telefon/servicii/taxi)!",
    "Aplicatiile pentru Staff sunt deschise pe discord!!",
    "Daca vrei sa iti faci un Gang, aplica pe discord ca (Lider Gang)",
    "Aplicatiile pentru Lider Medici sunt deschise pe discord!!",
    "Poti fi patron la un job, vei primii incasari cand cineva lucreaza acolo!",
    
}