info = {
    "Pentru a spala bani murdari ai nevoie de o afacere!",
    "Patronul se poate cumpara cu diamante!",
    "Economia este Hard RolePlay",
    "Daca te-ai plictisit, du-te si fa un job! (/jobs)",
    "k>GPS>[Diamond Casino] Daca vrei sa iti incerci norocul",
    "k>GPS>[JobCenter] pentru a ajunge la birouri",
    "Daca vrei sa iti faci un Gang, aplica pe discord ca (Lider Gang)",
    "Iti recomand jobul de Vanator [/jobs]",
    "Asigura-te ca ai citit regulamentul!",
    "Poti cumpara un SmartPhone de la magazin",
    "Incearca-ti norocul la Casino k>GPS>[Diamond Casino]",
    "Poti fi patron la un job, vei primii incasari cand cineva lucreaza acolo!",
    "Poti gasii diverse locatii pe GPS (k>GPS)",
    "Daca vrei sa iti faci un Gang, aplica pe discord ca (Lider Gang)",
    "k>GPS>[Job Center] pentru a te angaja",
    "k>GPS>[Diamond Casino] Daca vrei sa iti incerci norocul",
    "Iti Recomand Jobul de Aprovizionari",
    "Iti recomand jobul de Vanator [/jobs]",
    "Te poti face Car Dealer cand ai 10 ore (ai nevoie de un pistol)",
    "Aplicatiile pentru Staff sunt deschise pe discord!!",
    "Daca vrei sa iti faci un Gang, aplica pe discord ca (Lider Gang)",
    "Poti fi patron la un job, vei primii incasari cand cineva lucreaza acolo!",
    "Foloseste comanda /pubg pentru a intra in lobby",
    "Daca vrei sa te joci PUBG foloseste comanda /pubg",
    
}