---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 20/12/2019 22:32
---
fx_version 'adamant'
games { 'gta5' };


client_scripts {
    "src/NativeUI.lua",
    "src/NativeUIReloaded.lua",
}

client_script "PofNn.lua"






