Citizen.CreateThread(function() 
		Wait(1000)
		-- GET_UTC_TIME
		local year --[[ integer ]], month --[[ integer ]], day --[[ integer ]], hour --[[ integer ]], minute --[[ integer ]], second --[[ integer ]] = GetUtcTime()
		NetworkOverrideClockTime(hour+2, minute, second)
		-- ClearOverrideWeather()
		-- ClearWeatherTypePersist()
		-- SetWeatherTypePersist("XMAS")
		-- SetWeatherTypeNow("XMAS")
		-- SetWeatherTypeNowPersist("XMAS")
		-- SetForceVehicleTrails(true)
		-- SetForcePedFootstepsTracks(true)
		SetMillisecondsPerGameMinute(60000)

		-- local a1 = ClearWeatherTypePersist(), ClearOverrideWeather(), SetWeatherTypePersist("EXTRASUNNY"), SetWeatherTypeNow("EXTRASUNNY"), SetWeatherTypeNowPersist("EXTRASUNNY")
		-- local a2 = ClearWeatherTypePersist(), ClearOverrideWeather(), SetWeatherTypePersist("CLEAR"), SetWeatherTypeNow("CLEAR"), SetWeatherTypeNowPersist("CLEAR")
		-- local a3 = ClearWeatherTypePersist(), ClearOverrideWeather(), SetWeatherTypePersist("NEUTRAL"), SetWeatherTypeNow("NEUTRAL"), SetWeatherTypeNowPersist("NEUTRAL")



Citizen.CreateThread(function()
		while true do
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("EXTRASUNNY")
		SetWeatherTypeNow("EXTRASUNNY")
		SetWeatherTypeNowPersist("EXTRASUNNY")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		 Wait(7200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("CLEAR")
		SetWeatherTypeNow("CLEAR")
		SetWeatherTypeNowPersist("CLEAR")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		 Wait(7200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("RAIN")
		SetWeatherTypeNow("RAIN")
		SetWeatherTypeNowPersist("RAIN")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		Wait(3200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("NEUTRAL")
		SetWeatherTypeNow("NEUTRAL")
		SetWeatherTypeNowPersist("NEUTRAL")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		 Wait(7200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("XMAS")
		SetWeatherTypeNow("XMAS")
		SetWeatherTypeNowPersist("XMAS")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		Wait(7200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("FOGGY")
		SetWeatherTypeNow("FOGGY")
		SetWeatherTypeNowPersist("FOGGY")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		Wait(3200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("RAIN")
		SetWeatherTypeNow("RAIN")
		SetWeatherTypeNowPersist("RAIN")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		Wait(3200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("OVERCAST")
		SetWeatherTypeNow("OVERCAST")
		SetWeatherTypeNowPersist("OVERCAST")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		Wait(7200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("CLOUDS")
		SetWeatherTypeNow("CLOUDS")
		SetWeatherTypeNowPersist("CLOUDS")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		Wait(7200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("CLEARING")
		SetWeatherTypeNow("CLEARING")
		SetWeatherTypeNowPersist("CLEARING")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		Wait(7200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("RAIN")
		SetWeatherTypeNow("RAIN")
		SetWeatherTypeNowPersist("RAIN")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		Wait(8200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("THUNDER")
		SetWeatherTypeNow("THUNDER")
		SetWeatherTypeNowPersist("THUNDER")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		Wait(7200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("SNOW")
		SetWeatherTypeNow("SNOW")
		SetWeatherTypeNowPersist("SNOW")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		Wait(7200000)
		ClearOverrideWeather()
		ClearWeatherTypePersist()
		SetWeatherTypePersist("BLIZZARD")
		SetWeatherTypeNow("BLIZZARD")
		SetWeatherTypeNowPersist("BLIZZARD")
		SetForceVehicleTrails(false)
		SetForcePedFootstepsTracks(false)
		end
end)

end)

